name: Build
on: [push]

jobs:
  build:
    name: Build 11ty
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          command: build
