name: Build
on: [push]

jobs:
  Build-and-Deploy:
    name: Build 11ty
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: checkout code
        run: yarn build

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp.joshuazeltman.com
          ftp-username: jtz-admin-ftp@jtz.me
          ftp-password: ${{ secrets.JTZ_ADMIN_FTP }}
          git-ftp-args: --dry-run
          local-dir: _site
